// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $1 from "./routes/login.tsx";
import * as $2 from "./routes/logout.tsx";
import * as $$0 from "./islands/Start.tsx";
import * as $$1 from "./islands/Status.tsx";
import * as $$2 from "./islands/Stop.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
    "./routes/login.tsx": $1,
    "./routes/logout.tsx": $2,
  },
  islands: {
    "./islands/Start.tsx": $$0,
    "./islands/Status.tsx": $$1,
    "./islands/Stop.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
